repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=2"
          - "--no-sort-keys"
          - "--no-ensure-ascii"
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        args: [ "-rn", "-sn", "--rcfile=pylintrc", "--fail-on=I" ]
        exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/
      # We define an additional manual step to allow running pylint with a spelling
      # checker in CI.
      - id: pylint
        alias: pylint-with-spelling
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        args: [ "-rn", "-sn", "--rcfile=pylintrc", "--fail-on=I", "--spelling-dict=en" ]
        exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/
        stages: [ manual ]
      - id: fix-documentation
        name: Fix documentation
        entry: python3 -m script.fix_documentation
        language: system
        types: [ text ]
        files: ^(doc/whatsnew/\d+\.\d+\.rst)
      - id: check-newsfragments
        name: Check newsfragments
        entry: python3 -m script.check_newsfragments
        language: system
        types: [ text ]
        files: ^(doc/whatsnew/fragments)
        exclude: doc/whatsnew/fragments/_.*.rst